### ISSUE TITLE
Anchor-based metric with the IoU threshold of 0.7

### ISSUE THREAD

**Issue by jytime** [thangvubk/Cascade-RPN#1]
Hi,

Thanks for your great work. I am a bit curious about how you apply anchor-based metric to sample. 

Faster R-CNN sets a positive training IoU threshold and a negative IoU threshold. It keeps their numbers close to a ratio of 1:3. Since you only use one threshold, does this mean you only compute losses on those proposals with IoU higher than 0.7, and ignore others?

Best,
Jy

**Comment by thangvubk** [comment]
Hi Jy,
The IoU threshold 0.7 means: ``if IoU >= 0.7 sample is positive else negative``.
It can be considered that both the thresholds for positive and negative samples are set to 0.7. 
Check [here](https://github.com/thangvubk/Cascade-RPN/blob/3fa49f3475d845d2f40c5210d26cc428d1eedc98/configs/cascade_rpn/cascade_rpn_r50_fpn_1x.py#L66)

**Comment by jytime** [comment]
Hi Thang, 

Thank you for your reply. I would check the codes.

Best
