### ISSUE TITLE
How to install the project?

### ISSUE THREAD

**Issue by a9311072** [thangvubk/Cascade-RPN#21]
Hi,

can not found the related information by this repository?
could you share more info with me?
Thanks

**Comment by a9311072** [comment]
I found the installation doc as below
https://github.com/thangvubk/Cascade-RPN/tree/master/docs

**Comment by a9311072** [comment]
Based on the installation document, 
I can not build this project by docker
There are many issues dependency as below library
- mmcv
- mmdet
- pycocotools

Could anyone provide the related version?

Also, how can I download the pre-trained model for this project?
Thanks

**Comment by thangvubk** [comment]
Cascade RPN has been merged to mmdetection2, see [here](https://github.com/open-mmlab/mmdetection/pull/1900). Feel free to use Cascade RPN from mmdetection.

**Comment by a9311072** [comment]
Thanks for the reply.

I tried to use the cascade_rpn from mmdetector, but I can not get the **region proposal** result by the model. 
Do you have any advice?

---------------------------------------------------------------------------------------------------
config_file = '../configs/cascade_rpn/crpn_r50_caffe_fpn_1x_coco.py'
checkpoint_file = '../checkpoints/cascade_rpn_r50_caffe_fpn_1x_coco-7aa93cef.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
img = 'demo.jpg'
result = inference_detector(model, img)
show_result_pyplot(model, img, result)

/mmdetection/mmdet/datasets/utils.py:68: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)

**Comment by a9311072** [comment]
I found the issue was caused by the mmdet show_result()
Also, I did a workaround-fixed to move forward, thanks
