### ISSUE TITLE
Why do you use a single anchor per location?

### ISSUE THREAD

**Issue by bruceyang2012** [thangvubk/Cascade-RPN#3]
Hi，I wonder why you use a single anchor per location. Will you get a better result if using more anchor  ratios? Thanks.

**Comment by zlj199502** [comment]
I want to know about it too.

**Comment by thangvubk** [comment]
The are two reasons (1) remove hyper-parameter defined by anchor scales and ratios and (2) reduce overhead of feature sampling for adaptive conv. When using more scales, it is expected that the performance is at least comparable to 1 scale.

**Comment by zlj199502** [comment]
If I want using more anchors. How can I do the adaptive conv?

**Comment by thangvubk** [comment]
The feature sampling of adaptive convolution is controlled by the offsets. You need to modify [anchor_offset()](https://github.com/thangvubk/Cascade-RPN/blob/6a82abe23f02737167b4d24790acbc85e9a025f7/mmdet/core/anchor/anchor_offset.py#L4) to support multiple anchors per location.

**Comment by zlj199502** [comment]
Thank you for your reply. I mean if i get multiple offsets. How to combined with multiple anchor?

**Comment by thangvubk** [comment]
@zlj199502 you may need to utilize deformable group to use multiple multiple anchor.
