### ISSUE TITLE
url of model weight can't access

### ISSUE THREAD

**Issue by ZhuSiyuan** [thangvubk/Cascade-RPN#5]
Hello,

I want to get the model weight of crpn(Cascade R-CNN | Cascade RPN | R-50-FPN),
but http://bit.ly/crpn_cascade_rcnn_r50 can't access. 

Is there any other alternative?

Thx.

**Comment by thangvubk** [comment]
We can access the model weight using Google chrome browser. Can you check it again?

**Comment by ZhuSiyuan** [comment]
Oh, I think it should be the problem that the we can't access some overseas websites in China. Thank you for your reply.
