### ISSUE TITLE
Regression Statistics

### ISSUE THREAD

**Issue by RainHxj** [thangvubk/Cascade-RPN#7]
What does “regression statistics” mean？

**Comment by thangvubk** [comment]
They are the mean and std values computed from the training split.

**Comment by RainHxj** [comment]
Then， how to use it to improve the performance?

**Comment by thangvubk** [comment]
They are used in [here](https://github.com/thangvubk/Cascade-RPN/blob/c832973b8d849acbe4c0ebf75f353c7f48ec457b/configs/cascade_rpn/cascade_rpn_r50_fpn_1x.py#L28) and [here](https://github.com/thangvubk/Cascade-RPN/blob/c832973b8d849acbe4c0ebf75f353c7f48ec457b/configs/cascade_rpn/cascade_rpn_r50_fpn_1x.py#L45). The statistics aim to improve multi-task learning.
