### ISSUE TITLE
s0.loss_rpn_reg is always 0

### ISSUE THREAD

**Issue by jiyoon0630** [thangvubk/Cascade-RPN#8]
Hi! I'm June.
I'm so impressed with your idea of changing RPN in 2 stage detector.
And also thanks for well-organized Cascade-RPN code.

When I followed your instruction to train Cascade-RPN based Faster R-CNN, I found something strange.
![image](https://user-images.githubusercontent.com/32054860/74115341-2d283500-4bf2-11ea-94c5-caf16fa47594.png)
The problem is "s0.loss_rpn_reg is always 0".
It was same when to train only Cascade-RPN.

Is it normal to get zero of regression loss at the first rpn stage?
It would be a pleasure if you explain this phenomenon.

* Notes
(Training) python3 ./tools/train.py configs/cascade_rpn/cascade_rpn_r50_fpn_1x.py
(Datasets) coco
(Computing power) NVIDIA TITAN Xp
(versions) 
python 3.5.2
ubuntu 16.04
cudnn 7.0.5
cuda 9.0.176
gcc 5.4.0
nccl 2213

**Comment by jiyoon0630** [comment]
https://github.com/thangvubk/Cascade-RPN/issues/6#issue-535499408
I checked this issue. Since I use single GPU, I changed lr to 0.0025, however, s0.loss_rpn_loss is still 0.

**Comment by thangvubk** [comment]
I can train the network normally with 1 GPU. Can you try setup virtual env then reinstall everything from scratch?

**Comment by jiyoon0630** [comment]
Thanks @thangvubk 
I set up virtualenv and reinstall everything as you said. Finally, the problem has been solved. Now s0.loss_rpn_loss is non-zero value.

I think the main issue was a crash between some libraries.
I'll leave lists of packages in problem-solved and wrong cases.

By the way, thank you for fast reply and advice.

* Common versions
python 3.5.2
ubuntu 16.04
cudnn 7.0.5
cuda 9.0.176
gcc 5.4.0
nccl 2213

<Virtual env(problem-solved)>
![image](https://user-images.githubusercontent.com/32054860/74301575-d9a31c00-4d96-11ea-9f44-137955faabb2.png)
![image](https://user-images.githubusercontent.com/32054860/74301596-e758a180-4d96-11ea-8b16-d4a204e9f759.png)

<Original(wrong)>
![image](https://user-images.githubusercontent.com/32054860/74301624-fe978f00-4d96-11ea-9c92-5afcac1acf89.png)
![image](https://user-images.githubusercontent.com/32054860/74301646-0f480500-4d97-11ea-80cf-c7cd05f3d5c3.png)
![image](https://user-images.githubusercontent.com/32054860/74301658-1a9b3080-4d97-11ea-91b4-096d953f712d.png)
