### ISSUE TITLE
Which code is play the effect of restriction below Eqs 7 in Section 4.1?

### ISSUE THREAD

**Issue by aimhabo** [thangvubk/Cascade-RPN#9]
In paper's **section 4.1** says that:

> 1. 𝑦[𝑝]=∑_(𝑜∈𝑂)▒〖𝑤[𝑜]∙𝑥[𝑝+𝑜]〗
> 2. 𝑂=𝑂_𝑐𝑡𝑟+𝑂_𝑠ℎ𝑝
> 3. 𝑂_𝑠ℎ𝑝={ (±(𝑎_𝑤^)/2 𝑜𝑟 0,±(𝑎_ℎ^)/2 𝑜𝑟 0)} )

I don't quite understand the operation referred to line 3. Could you please to point out what parts does it include in the code?

**Comment by thangvubk** [comment]
Please check [here](https://github.com/thangvubk/Cascade-RPN/blob/c832973b8d849acbe4c0ebf75f353c7f48ec457b/mmdet/core/anchor/anchor_offset.py#L17)

**Comment by aimhabo** [comment]
@thangvubk Thank you very much!
